# Generated by Django 3.0.7 on 2020-09-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200903_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
