# Generated by Django 3.0.7 on 2020-09-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200917_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descriptions',
            new_name='description',
        ),
    ]
