# Generated by Django 3.0.7 on 2020-09-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200903_1314'),
        ('accounts', '0002_useraccountevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='eventos',
            field=models.ManyToManyField(through='accounts.UserAccountEvent', to='events.Event'),
        ),
    ]
