# Generated by Django 3.0.7 on 2020-09-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_eventos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountevent',
            name='quantity',
        ),
    ]
