# Generated by Django 3.0.7 on 2020-09-09 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccountevent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountevent',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
